apiVersion: batch/v1
kind: Job
metadata:
  name: e2etest100k.2
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: entityservice
        tier: aux
        run: entitytester
    spec:
      restartPolicy: Never
      containers:
      - name: entitytester
        image: quay.io/n1analytics/entity-app:v1.5.3
        imagePullPolicy: Always
        env:
          - name: ENTITY_SERVICE_URL
            value: http://entityservice-api/api/v1
          - name: ENTITY_SERVICE_TEST_SIZE
            value: "100000"
          - name: ENTITY_SERVICE_TEST_REPEATS
            value: "1"
#          - name: ENTITY_SERVICE_PERMUTATION
#            value: "true"
          - name: LOGGING_LEVEL
            value: "INFO"
        command:
          - "python"
          - "test_service.py"
      imagePullSecrets:
        - name: n1analytics-coreos-pull-secret
