apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entityservice-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: entityservice
        tier: frontend
        run: entityservice-api
    spec:
      containers:
      - name: entityservice-nginx
        image: quay.io/n1analytics/entity-nginx:v1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8851
          name: entity-nginx
        env:
          - name: TARGET_SERVICE
            value: localhost
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["/usr/sbin/nginx","-s","quit"]
      - name: entityservice-flask
        image: quay.io/n1analytics/entity-app:v1.2.1
        imagePullPolicy: Always
        env:
          - name: REDIS_SERVER
            value: entityservice-redis
          - name: DATABASE_SERVER
            value: entityservice-db
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: entityservice-db-password
                key: db-password.txt
          - name: DEBUG
            value: "false"
        ports:
          - containerPort: 8000
            name: entity-flask
      imagePullSecrets:
            - name: n1analytics-coreos-pull-secret
