apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entityservice-api
spec:
  replicas: {{ .Values.api.Replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: frontend
        run: entityservice-api
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: entityservice-nginx
        image: {{ .Values.api.imageRegistery}}/{{ .Values.api.www.image }}:{{ .Values.api.www.tag }}
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.api.www.memory }}

        ports:
        - containerPort: {{ .Values.api.www.containerPort }}
          name: entity-nginx
        env:
          - name: TARGET_SERVICE
            value: localhost
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["/usr/sbin/nginx","-s","quit"]
      - name: entityservice-flask
        image: {{ .Values.api.imageRegistery }}/{{ .Values.api.app.image }}:{{ .Values.api.app.tag }}
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.api.app.memory }}
        env:
          - name: REDIS_SERVER
            value: "{{ .Release.Name }}-{{ .Values.redis.nameOverride }}"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: redisPassword
          - name: DATABASE_SERVER
            value: "{{ .Release.Name }}-{{ .Values.postgresql.nameOverride }}"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: postgresPassword
          - name: DEBUG
            value: {{default "false" .Values.api.app.debug | quote }}
          - name: MINIO_SERVER
            value: "{{ .Release.Name }}-minio-svc:9000"
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: minioSecretKey
        ports:
          - containerPort: {{ .Values.api.app.containerPort }}
            name: entity-flask
        livenessProbe:
          httpGet:
            path: /status
            port: entity-flask
          initialDelaySeconds: 10
          periodSeconds: 300
          timeoutSeconds: 30
      imagePullSecrets:
        - name: n1analytics-coreos-pull-secret
