apiVersion: v1
kind: Secret
metadata:
  name: es-credentials
  labels:
    app: {{ template "fullname" . }}
  annotations:
    #"helm.sh/hook": pre-install
data:
  postgresPassword: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  redisPassword: {{ .Values.redis.redisPassword | b64enc | quote }}
  minioAccessKey: {{ .Values.minio.accessKey | b64enc | quote }}
  minioSecretKey: {{ .Values.minio.secretKey | b64enc | quote }}
