{{- if .Values.workers.monitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-monitor
  labels:
    app: entityservice
spec:
  ports:
    - port: 80
      name: http
      targetPort: "celery-monitor"
  selector:
    app: {{ template "fullname" . }}
    tier: aux
    run: celery-monitor
{{- end }}
