apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entityservice-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: entityservice
        tier: aux
        run: celery-monitor
    spec:
      containers:
      - name: celery-monitor
        image: quay.io/n1analytics/entity-app:{{ .Values.api.www.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8888
            name: celery-monitor
        command:
          - "/usr/local/bin/celery"
          - "-A"
          - "async_worker"
          - "flower"
          - "--port=8888"
          - "--broker=redis://:{{ .Values.redis.redisPassword }}@{{ .Release.Name }}-{{ .Values.redis.nameOverride }}:6379/0"
#          - "--url_prefix=monitor"
      imagePullSecrets:
        - name: n1analytics-coreos-pull-secret
