{{- if .Values.workers.monitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}-monitor
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.api.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      name: http
      targetPort: "celery-monitor"
  selector:
    app: {{ template "fullname" . }}
    tier: aux
    run: celery-monitor
{{- end }}
