apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entityservice-worker
spec:
  replicas: {{ .Values.workers.replicas }}
  template:
    metadata:
      labels:
        app: entityservice
        tier: backend
        run: entityservice-worker
    spec:
      containers:
      - name: celery-worker
        image: {{ .Values.workers.imageRegistery }}/{{ .Values.workers.image }}:{{ .Values.workers.tag }}
        imagePullPolicy: Always
        env:
          - name: REDIS_SERVER
            value: {{ .Release.Name }}-redis
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: redisPassword
          - name: DATABASE_SERVER
            value: "es-postgres"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: postgresPassword
          - name: DEBUG
            value: {{ .Values.workers.debug | quote }}
          - name: ENTITY_MATCH_THRESHOLD
            value: "0.95"
          - name: GREEDY_CHUNK_SIZE
            value: "1000000000"
          - name: ENCRYPTION_MIN_KEY_LENGTH
            value: "1024"
          - name: MINIO_SERVER
            value: {{ .Release.Name }}-minio-svc:9000
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: es-credentials
                key: minioSecretKey

        command:
          - "/usr/local/bin/celery"
          - "-A"
          - "async_worker"
          - "worker"
          - "--loglevel=info"
      imagePullSecrets:
        - name: n1analytics-coreos-pull-secret
