## https://kubernetes.io/docs/user-guide/compute-resources

api:
  app:
    resources:
      limits:
        memory: 512Mi
        cpu: 50m
      requests:
        cpu: 50m
        memory: 256Mi


  dbinit:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi


workers:
  replicaCount: 1

  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 512Mi
      cpu: 200m
  highmemory:
    replicaCount: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

postgresql:
  resources:
    limits:
      memory: 200Mi
    requests:
      memory: 100Mi
      cpu: 50m

  persistence:
    size: 1Gi


minio:
  persistence:
    enabled: false
    size: 1Gi

redis-ha:
  resources:
    server:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 1Gi
    sentinel:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 1Gi