dependencies:
  - name: redis-ha
    version: 2.1.3
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: minio
    version: 1.3.3
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: postgresql
    version: 0.13.1
    repository: https://kubernetes-charts.storage.googleapis.com
