dependencies:
  - name: redis
    version: 0.4.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: minio
    version: 0.1.4
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: postgresql
    version: 0.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
