apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entityservice-api
spec:
  replicas: {{ .Values.api.Replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: frontend
        run: entityservice-api
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: entityservice-nginx
        image: {{ .Values.api.imageRegistery}}/{{ .Values.api.www.image }}:{{ .Values.api.www.tag }}
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.api.www.memory }}

        ports:
        - containerPort: {{ .Values.api.www.containerPort }}
          name: entity-nginx
        env:
          - name: TARGET_SERVICE
            value: localhost
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["/usr/sbin/nginx","-s","quit"]
      - name: entityservice-flask
        image: {{ .Values.api.imageRegistery }}/{{ .Values.api.app.image }}:{{ .Values.api.app.tag }}
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.api.app.memory }}
        env:
          - name: REDIS_SERVER
            value: entityservice-redis
          - name: DATABASE_SERVER
            value: entityservice-db
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: entityservice-db-password
                key: db-password.txt
          - name: DEBUG
            value: {{default "false" .Values.api.app.debug }}
        ports:
          - containerPort: {{ .Values.api.app.containerPort }}
            name: entity-flask
      imagePullSecrets:
        - name: n1analytics-coreos-pull-secret
