apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-auto-scale
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: entityservice-worker
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 75
