{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notebook-ingress
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: jupyter-nb-service
          servicePort: 80
{{- end }}
