apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nb-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
