apiVersion: v1
kind: Service
metadata:
  name: jupyter-nb-service
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: jupyter
    targetPort: "jupyter-nb"
  selector:
    app: {{ template "fullname" . }}
    run: jupyter
