kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: amazonEBS
    app: entityservice
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    # ideally we set up dynamic provisioning of storage
    volumeID: vol-0bbfd88d0681e4cb6
    fsType: ext4



