apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entityservice-minio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: minio
        app: entityservice
        tier: data
    spec:
      containers:
      - name: entityservice-minio
        image: minio/minio
        command:
          - "server"
          - "/export"
        ports:
        - containerPort: 6379
