apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: entityservice
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  annotations:
    #"helm.sh/hook": pre-install
type: Opaque
data:
  postgresPassword: {{ .Values.postgresPassword | b64enc | quote }}
