apiVersion: v1
kind: Service
metadata:
  name: es-postgres
  labels:
    app: entityservice
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "fullname" . }}
