apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entityservice-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: entityservice
        tier: data
        run: postgres
    spec:
      containers:
      - image: quay.io/n1analytics/entity-db-server:v1.1
        name: entityservice-db
        env:
        - name: POSTGRES_PASSWORD
          # Added to cluster with:
          # kubectl create secret generic entityservice-db-password --from-file=db-password.txt
          # Get the new secret resource description with
          # kubectl get secret entityservice-db-password -o yaml
          valueFrom:
            secretKeyRef:
              name: entityservice-db-password
              key: db-password.txt
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: "/var/lib/postgresql"
          # Note we can't mount to /var/lib/postgresql/data
          # as aws ebs seems to include a "Lost and Found" directory
          # which postgres gets upset about.
          name: db-volume
      imagePullSecrets:
      - name: n1analytics-coreos-pull-secret
      volumes:
      # A persistent storage claim...
      - name: db-volume
        persistentVolumeClaim:
          claimName: es-db-pv-claim
# For testing
#      - name: db-volume
#        emptyDir: {}
