version: '2'
services:

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=rX%QpV7Xgyrz
    volumes:
      - ../../dockerBootstrap/etc/entity/db:/docker-entrypoint-initdb.d:ro
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis

  # The application server
  backend:
    image: quay.io/n1analytics/entity-app
    volumes:
      - ../logging:/var/log
    environment:
      - DEBUG=true
      - DATABASE_PASSWORD=rX%QpV7Xgyrz
      - LOGFILE=/var/log/entity-service-app.log
    depends_on:
      - db
      - redis
      - worker

  # A celery worker
  worker:
    image: quay.io/n1analytics/entity-app
    depends_on:
      - redis
      - db
    entrypoint: celery -A async_worker worker --loglevel=debug --beat --concurrency=10 -n entity-worker
    environment:
      - DATABASE_PASSWORD=rX%QpV7Xgyrz
      - LOGFILE=/var/log/entity-service-worker-A.log

  nginx:
    image: quay.io/n1analytics/entity-nginx
    ports:
      - 8851:80
    depends_on:
      - backend

